"""initial schema

Revision ID: 3f054a3b0c82
Revises: 
Create Date: 2026-05-29 01:46:54.985069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3f054a3b0c82'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('confidence_threshold', sa.Float(), nullable=False),
    sa.Column('gestational_age_policy_weeks', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('donors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('tissue_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.String(), nullable=True),
    sa.Column('evaluation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_donors_tenant_id'), 'donors', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('audit_entries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('donor_id', sa.String(), nullable=True),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('detail', sa.String(), nullable=False),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['donor_id'], ['donors.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_entries_action'), 'audit_entries', ['action'], unique=False)
    op.create_index(op.f('ix_audit_entries_donor_id'), 'audit_entries', ['donor_id'], unique=False)
    op.create_index(op.f('ix_audit_entries_tenant_id'), 'audit_entries', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_audit_entries_timestamp'), 'audit_entries', ['timestamp'], unique=False)
    op.create_table('donor_documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('donor_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['donor_id'], ['donors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_donor_documents_donor_id'), 'donor_documents', ['donor_id'], unique=False)
    op.create_index(op.f('ix_donor_documents_tenant_id'), 'donor_documents', ['tenant_id'], unique=False)
    op.create_table('extracted_fields',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('donor_id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('citation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('flagged_low_confidence', sa.Boolean(), nullable=False),
    sa.Column('reviewed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['donor_documents.id'], ),
    sa.ForeignKeyConstraint(['donor_id'], ['donors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_fields_document_id'), 'extracted_fields', ['document_id'], unique=False)
    op.create_index(op.f('ix_extracted_fields_donor_id'), 'extracted_fields', ['donor_id'], unique=False)
    op.create_index(op.f('ix_extracted_fields_tenant_id'), 'extracted_fields', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extracted_fields_tenant_id'), table_name='extracted_fields')
    op.drop_index(op.f('ix_extracted_fields_donor_id'), table_name='extracted_fields')
    op.drop_index(op.f('ix_extracted_fields_document_id'), table_name='extracted_fields')
    op.drop_table('extracted_fields')
    op.drop_index(op.f('ix_donor_documents_tenant_id'), table_name='donor_documents')
    op.drop_index(op.f('ix_donor_documents_donor_id'), table_name='donor_documents')
    op.drop_table('donor_documents')
    op.drop_index(op.f('ix_audit_entries_timestamp'), table_name='audit_entries')
    op.drop_index(op.f('ix_audit_entries_tenant_id'), table_name='audit_entries')
    op.drop_index(op.f('ix_audit_entries_donor_id'), table_name='audit_entries')
    op.drop_index(op.f('ix_audit_entries_action'), table_name='audit_entries')
    op.drop_table('audit_entries')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_donors_tenant_id'), table_name='donors')
    op.drop_table('donors')
    op.drop_table('tenants')
    # ### end Alembic commands ###
