/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated.audit'
import { Route as AuthenticatedDonorsIndexRouteImport } from './routes/_authenticated.donors.index'
import { Route as AuthenticatedDonorsNewRouteImport } from './routes/_authenticated.donors.new'
import { Route as AuthenticatedDonorsIdRouteImport } from './routes/_authenticated.donors.$id'
import { Route as AuthenticatedDonorsIdReportRouteImport } from './routes/_authenticated.donors.$id_.report'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDonorsIndexRoute =
  AuthenticatedDonorsIndexRouteImport.update({
    id: '/donors/',
    path: '/donors/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDonorsNewRoute = AuthenticatedDonorsNewRouteImport.update({
  id: '/donors/new',
  path: '/donors/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDonorsIdRoute = AuthenticatedDonorsIdRouteImport.update({
  id: '/donors/$id',
  path: '/donors/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDonorsIdReportRoute =
  AuthenticatedDonorsIdReportRouteImport.update({
    id: '/donors/$id_/report',
    path: '/donors/$id/report',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/donors/$id': typeof AuthenticatedDonorsIdRoute
  '/donors/new': typeof AuthenticatedDonorsNewRoute
  '/donors/': typeof AuthenticatedDonorsIndexRoute
  '/donors/$id/report': typeof AuthenticatedDonorsIdReportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/donors/$id': typeof AuthenticatedDonorsIdRoute
  '/donors/new': typeof AuthenticatedDonorsNewRoute
  '/donors': typeof AuthenticatedDonorsIndexRoute
  '/donors/$id/report': typeof AuthenticatedDonorsIdReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/donors/$id': typeof AuthenticatedDonorsIdRoute
  '/_authenticated/donors/new': typeof AuthenticatedDonorsNewRoute
  '/_authenticated/donors/': typeof AuthenticatedDonorsIndexRoute
  '/_authenticated/donors/$id_/report': typeof AuthenticatedDonorsIdReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/audit'
    | '/settings'
    | '/donors/$id'
    | '/donors/new'
    | '/donors/'
    | '/donors/$id/report'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/audit'
    | '/settings'
    | '/donors/$id'
    | '/donors/new'
    | '/donors'
    | '/donors/$id/report'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/audit'
    | '/_authenticated/settings'
    | '/_authenticated/donors/$id'
    | '/_authenticated/donors/new'
    | '/_authenticated/donors/'
    | '/_authenticated/donors/$id_/report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/donors/': {
      id: '/_authenticated/donors/'
      path: '/donors'
      fullPath: '/donors/'
      preLoaderRoute: typeof AuthenticatedDonorsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/donors/new': {
      id: '/_authenticated/donors/new'
      path: '/donors/new'
      fullPath: '/donors/new'
      preLoaderRoute: typeof AuthenticatedDonorsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/donors/$id': {
      id: '/_authenticated/donors/$id'
      path: '/donors/$id'
      fullPath: '/donors/$id'
      preLoaderRoute: typeof AuthenticatedDonorsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/donors/$id_/report': {
      id: '/_authenticated/donors/$id_/report'
      path: '/donors/$id/report'
      fullPath: '/donors/$id/report'
      preLoaderRoute: typeof AuthenticatedDonorsIdReportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedDonorsIdRoute: typeof AuthenticatedDonorsIdRoute
  AuthenticatedDonorsNewRoute: typeof AuthenticatedDonorsNewRoute
  AuthenticatedDonorsIndexRoute: typeof AuthenticatedDonorsIndexRoute
  AuthenticatedDonorsIdReportRoute: typeof AuthenticatedDonorsIdReportRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedDonorsIdRoute: AuthenticatedDonorsIdRoute,
  AuthenticatedDonorsNewRoute: AuthenticatedDonorsNewRoute,
  AuthenticatedDonorsIndexRoute: AuthenticatedDonorsIndexRoute,
  AuthenticatedDonorsIdReportRoute: AuthenticatedDonorsIdReportRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
