/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DonorsIndexRouteImport } from './routes/donors.index'
import { Route as DonorsIdRouteImport } from './routes/donors.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DonorsIndexRoute = DonorsIndexRouteImport.update({
  id: '/donors/',
  path: '/donors/',
  getParentRoute: () => rootRouteImport,
} as any)
const DonorsIdRoute = DonorsIdRouteImport.update({
  id: '/donors/$id',
  path: '/donors/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/donors/$id': typeof DonorsIdRoute
  '/donors/': typeof DonorsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/donors/$id': typeof DonorsIdRoute
  '/donors': typeof DonorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/donors/$id': typeof DonorsIdRoute
  '/donors/': typeof DonorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/donors/$id' | '/donors/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/donors/$id' | '/donors'
  id: '__root__' | '/' | '/donors/$id' | '/donors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DonorsIdRoute: typeof DonorsIdRoute
  DonorsIndexRoute: typeof DonorsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donors/': {
      id: '/donors/'
      path: '/donors'
      fullPath: '/donors/'
      preLoaderRoute: typeof DonorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donors/$id': {
      id: '/donors/$id'
      path: '/donors/$id'
      fullPath: '/donors/$id'
      preLoaderRoute: typeof DonorsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DonorsIdRoute: DonorsIdRoute,
  DonorsIndexRoute: DonorsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
