/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated.audit'
import { Route as AuthenticatedDonorsIndexRouteImport } from './routes/_authenticated.donors.index'
import { Route as AuthenticatedDonorsNewRouteImport } from './routes/_authenticated.donors.new'
import { Route as AuthenticatedDonorsIdRouteImport } from './routes/_authenticated.donors.$id'
import { Route as AuthenticatedDonorsIdReportRouteImport } from './routes/_authenticated.donors.$id.report'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/_authenticated/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/_authenticated/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDonorsIndexRoute =
  AuthenticatedDonorsIndexRouteImport.update({
    id: '/_authenticated/donors/',
    path: '/donors/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedDonorsNewRoute = AuthenticatedDonorsNewRouteImport.update({
  id: '/_authenticated/donors/new',
  path: '/donors/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDonorsIdRoute = AuthenticatedDonorsIdRouteImport.update({
  id: '/_authenticated/donors/$id',
  path: '/donors/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDonorsIdReportRoute =
  AuthenticatedDonorsIdReportRouteImport.update({
    id: '/report',
    path: '/report',
    getParentRoute: () => AuthenticatedDonorsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/donors/$id': typeof AuthenticatedDonorsIdRouteWithChildren
  '/donors/new': typeof AuthenticatedDonorsNewRoute
  '/donors/': typeof AuthenticatedDonorsIndexRoute
  '/donors/$id/report': typeof AuthenticatedDonorsIdReportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/donors/$id': typeof AuthenticatedDonorsIdRouteWithChildren
  '/donors/new': typeof AuthenticatedDonorsNewRoute
  '/donors': typeof AuthenticatedDonorsIndexRoute
  '/donors/$id/report': typeof AuthenticatedDonorsIdReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/donors/$id': typeof AuthenticatedDonorsIdRouteWithChildren
  '/_authenticated/donors/new': typeof AuthenticatedDonorsNewRoute
  '/_authenticated/donors/': typeof AuthenticatedDonorsIndexRoute
  '/_authenticated/donors/$id/report': typeof AuthenticatedDonorsIdReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/audit'
    | '/settings'
    | '/donors/$id'
    | '/donors/new'
    | '/donors/'
    | '/donors/$id/report'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/audit'
    | '/settings'
    | '/donors/$id'
    | '/donors/new'
    | '/donors'
    | '/donors/$id/report'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/signup'
    | '/_authenticated/audit'
    | '/_authenticated/settings'
    | '/_authenticated/donors/$id'
    | '/_authenticated/donors/new'
    | '/_authenticated/donors/'
    | '/_authenticated/donors/$id/report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedDonorsIdRoute: typeof AuthenticatedDonorsIdRouteWithChildren
  AuthenticatedDonorsNewRoute: typeof AuthenticatedDonorsNewRoute
  AuthenticatedDonorsIndexRoute: typeof AuthenticatedDonorsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/donors/': {
      id: '/_authenticated/donors/'
      path: '/donors'
      fullPath: '/donors/'
      preLoaderRoute: typeof AuthenticatedDonorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/donors/new': {
      id: '/_authenticated/donors/new'
      path: '/donors/new'
      fullPath: '/donors/new'
      preLoaderRoute: typeof AuthenticatedDonorsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/donors/$id': {
      id: '/_authenticated/donors/$id'
      path: '/donors/$id'
      fullPath: '/donors/$id'
      preLoaderRoute: typeof AuthenticatedDonorsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/donors/$id/report': {
      id: '/_authenticated/donors/$id/report'
      path: '/report'
      fullPath: '/donors/$id/report'
      preLoaderRoute: typeof AuthenticatedDonorsIdReportRouteImport
      parentRoute: typeof AuthenticatedDonorsIdRoute
    }
  }
}

interface AuthenticatedDonorsIdRouteChildren {
  AuthenticatedDonorsIdReportRoute: typeof AuthenticatedDonorsIdReportRoute
}

const AuthenticatedDonorsIdRouteChildren: AuthenticatedDonorsIdRouteChildren = {
  AuthenticatedDonorsIdReportRoute: AuthenticatedDonorsIdReportRoute,
}

const AuthenticatedDonorsIdRouteWithChildren =
  AuthenticatedDonorsIdRoute._addFileChildren(
    AuthenticatedDonorsIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedDonorsIdRoute: AuthenticatedDonorsIdRouteWithChildren,
  AuthenticatedDonorsNewRoute: AuthenticatedDonorsNewRoute,
  AuthenticatedDonorsIndexRoute: AuthenticatedDonorsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
